FROM node:18

WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./

RUN npm install

COPY . .

# Compile os arquivos TypeScript para JavaScript
RUN npm run build

EXPOSE 3000

# Inicia o servidor com o código JavaScript gerado
CMD ["npm", "start"]
