# ARQUIVO DE CONFIGURAÇÃO DO DOCKER PARA O BANCO DE DADOS
version: '3.9'

services:
  app:
  build:
    context: .
    dockerfile: DockerFile
  ports:
    - "3000:3000"
  environment:
    - NODE_ENV=production
  volumes:
    - .:/app
  depends_on:
    - db
  db: 
    image: postgres
    container_name: empregados
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local