FROM node:18

WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./

RUN npm install

COPY . .

# Gera os arquivos do Prisma
RUN npx prisma generate

# Compila o código TypeScript
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]